apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: openelb-agent
spec:
  template:
    spec:
      containers:
        # Change the value of image field below to your controller image URL
        - image: anurag199/openelb-agent:v0.6.3
          name: openelb-agent
