apiVersion: apps/v1
kind: Deployment
metadata:
  name: openelb-manager
spec:
  template:
    spec:
      containers:
        # Change the value of image field below to your controller image URL
        - image: anurag199/openelb:v0.60.0
          name: openelb-manager
          resources:
            limits:
              cpu: 100m
              memory: 300Mi
            requests:
              cpu: 100m
              memory: 100Mi
